language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - CI=false pip install numpy-quaternion

# command to run tests
script:
  - python setup.py build_ext --inplace
  - PYTHONPATH=$PWD:$PYTHONPATH py.test
